kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-data
  labels:
    container.training/pv: ""
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/my-pv2
  #storageClassName: my-sc
  #claimRef:
  #  kind: PersistentVolumeClaim
  #  apiVersion: v1
  #  namespace: default
  #  name: my-pvc-XYZ45